services:

  hotels:
    image: limhinavarro95/ms-hotels:latest
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - limhinavarro-network

  rooms:
    image: limhinavarro95/ms-rooms:latest
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
      - limhinavarro-network

  reservations:
    image: limhinavarro95/ms-reservations:latest
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - limhinavarro-network

networks:
  limhinavarro-network: